import { PUBLIC_PROJECT_ID_SET } from "@/data/portfolio-curation"
import type {
  AdaptiveCapability,
  EvidenceRecord,
} from "../../../packages/adaptive-focus-core/src"

const projectPath = (projectId: string) => `/projects/${projectId}`
const professionalExperiencePath = "/about#professional-experience"

export const EVIDENCE_CATALOG: EvidenceRecord[] = [
  {
    id: "employment-astrocade-hitl",
    entityId: "employment-astrocade",
    capability: "human-in-the-loop-ai",
    statement:
      "Operated human review workflows for AI-generated game content across UGC quality, QA, final review, and creator-facing feedback.",
    sourcePath: professionalExperiencePath,
    evidenceType: "implemented",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "employment-astrocade-evaluation",
    entityId: "employment-astrocade",
    capability: "evaluation-calibration",
    statement:
      "Used structured evaluation and calibration practices to make automated content decisions more reviewable and consistent with human judgment.",
    sourcePath: professionalExperiencePath,
    evidenceType: "implemented",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "employment-astrocade-moderation",
    entityId: "employment-astrocade",
    capability: "moderation-qa",
    statement:
      "Improved QA annotation, reviewer sampling, documentation, and operational guardrails under production publishing constraints.",
    sourcePath: professionalExperiencePath,
    evidenceType: "implemented",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "employment-astrocade-operations",
    entityId: "employment-astrocade",
    capability: "operational-ux",
    statement:
      "Improved repeated review and publishing workflows for an AI-powered game creation platform.",
    sourcePath: professionalExperiencePath,
    evidenceType: "implemented",
    ownership: "contributed",
    confidence: "supporting",
  },
  {
    id: "employment-astrocade-creators",
    entityId: "employment-astrocade",
    capability: "creator-systems",
    statement:
      "Supported creator-facing publishing and feedback workflows inside an AI-powered game creation platform.",
    sourcePath: professionalExperiencePath,
    evidenceType: "implemented",
    ownership: "contributed",
    confidence: "direct",
  },
  {
    id: "employment-snorkel-model-evaluation",
    entityId: "employment-snorkel",
    capability: "model-evaluation",
    statement:
      "Authored and validated high-difficulty, graduate-level problems and assessed AI-generated responses for rigor, correctness, and reasoning quality.",
    sourcePath: professionalExperiencePath,
    evidenceType: "implemented",
    ownership: "contributed",
    confidence: "direct",
  },
  {
    id: "employment-snorkel-training-data",
    entityId: "employment-snorkel",
    capability: "training-data-development",
    statement:
      "Contributed expert-authored and validated examples to proprietary datasets used for LLM fine-tuning, benchmarking, and reinforcement learning.",
    sourcePath: professionalExperiencePath,
    evidenceType: "implemented",
    ownership: "contributed",
    confidence: "direct",
  },
  {
    id: "employment-snorkel-prompt-engineering",
    entityId: "employment-snorkel",
    capability: "prompt-engineering",
    statement:
      "Applied prompt engineering to reasoning and graduate-level knowledge tasks.",
    sourcePath: professionalExperiencePath,
    evidenceType: "implemented",
    ownership: "contributed",
    confidence: "direct",
  },
  {
    id: "employment-snorkel-evaluation-calibration",
    entityId: "employment-snorkel",
    capability: "evaluation-calibration",
    statement:
      "Identified reasoning flaws and refined model outputs through structured validation and error analysis.",
    sourcePath: professionalExperiencePath,
    evidenceType: "implemented",
    ownership: "contributed",
    confidence: "direct",
  },
  {
    id: "employment-snorkel-hitl",
    entityId: "employment-snorkel",
    capability: "human-in-the-loop-ai",
    statement:
      "Applied subject-matter expertise as a human evaluator inside an AI model-improvement workflow.",
    sourcePath: professionalExperiencePath,
    evidenceType: "implemented",
    ownership: "contributed",
    confidence: "direct",
  },
  {
    id: "employment-ford-workflow",
    entityId: "employment-ford",
    capability: "workflow-design",
    statement:
      "Developed a production workflow system for manufacturing time studies and operational review.",
    sourcePath: professionalExperiencePath,
    evidenceType: "shipped",
    ownership: "built",
    outcome: "Deployed as a production manufacturing system.",
    confidence: "direct",
  },
  {
    id: "employment-ford-operational-ux",
    entityId: "employment-ford",
    capability: "operational-ux",
    statement:
      "Translated repeated manufacturing processes into interactive production tooling.",
    sourcePath: professionalExperiencePath,
    evidenceType: "shipped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "employment-ford-design-engineering",
    entityId: "employment-ford",
    capability: "design-engineering",
    statement:
      "Built Unity3D and WebGL interfaces that connected manufacturing workflow requirements with working software.",
    sourcePath: professionalExperiencePath,
    evidenceType: "shipped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "employment-ford-data-visualization",
    entityId: "employment-ford",
    capability: "data-visualization",
    statement: "Created interactive analytics views for operations and stakeholder review.",
    sourcePath: professionalExperiencePath,
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "employment-ford-internal-tools",
    entityId: "employment-ford",
    capability: "internal-tools",
    statement:
      "Contributed to a production internal system used in manufacturing environments.",
    sourcePath: professionalExperiencePath,
    evidenceType: "shipped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "employment-starbucks-spatial",
    entityId: "employment-starbucks",
    capability: "xr-spatial",
    statement:
      "Designed Unity and mobile spatial prototypes for exploratory learning and operations concepts.",
    sourcePath: professionalExperiencePath,
    evidenceType: "prototyped",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "employment-starbucks-voice",
    entityId: "employment-starbucks",
    capability: "voice-interaction",
    statement:
      "Built a React speech-to-text prototype for a high-noise retail communication workflow.",
    sourcePath: professionalExperiencePath,
    evidenceType: "prototyped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "employment-starbucks-accessibility",
    entityId: "employment-starbucks",
    capability: "accessibility",
    statement:
      "Used accessibility research and usability evaluation to test communication and interaction concepts.",
    sourcePath: professionalExperiencePath,
    evidenceType: "researched",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "employment-starbucks-prototyping",
    entityId: "employment-starbucks",
    capability: "prototyping",
    statement:
      "Created high-fidelity flows and experimental prototypes to validate concepts before production decisions.",
    sourcePath: professionalExperiencePath,
    evidenceType: "prototyped",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "employment-starbucks-operational-ux",
    entityId: "employment-starbucks",
    capability: "operational-ux",
    statement:
      "Translated retail learning and communication workflows into testable emerging-technology concepts.",
    sourcePath: professionalExperiencePath,
    evidenceType: "prototyped",
    ownership: "designed",
    confidence: "supporting",
  },
  {
    id: "wizzo-ai-system",
    entityId: "wizzo",
    capability: "ai-product-systems",
    statement:
      "Designed and shipped an AI-native product system combining mentor chat, execution-aware memory, tools, quests, and connected work context.",
    sourcePath: projectPath("wizzo"),
    sourceSection: "Results - AI Product Proof",
    evidenceType: "shipped",
    ownership: "led",
    outcome: "Shipped a public beta with a live AI mentor and connected work context.",
    confidence: "direct",
  },
  {
    id: "wizzo-full-stack",
    entityId: "wizzo",
    capability: "design-engineering",
    statement:
      "Built the product with Next.js, TypeScript, Postgres, Drizzle, Neon, Vercel, OpenAI integrations, and Google workspace connectors.",
    sourcePath: projectPath("wizzo"),
    sourceSection: "Actions - Full-Stack Implementation",
    evidenceType: "shipped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "wizzo-product-ownership",
    entityId: "wizzo",
    capability: "product-ownership",
    statement:
      "Owned the product architecture across chat, memory, quest tracking, achievements, and connector-backed work context.",
    sourcePath: projectPath("wizzo"),
    sourceSection: "Actions - Product System Architecture",
    evidenceType: "designed",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "wizzo-workflows",
    entityId: "wizzo",
    capability: "workflow-design",
    statement:
      "Created mentor workflows for goal planning, progress reflection, grounded research, connected notes, and voice-supported follow-up.",
    sourcePath: projectPath("wizzo"),
    sourceSection: "Actions - AI Workflow Surfaces",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "wizzo-trust-controls",
    entityId: "wizzo",
    capability: "privacy-trust",
    statement:
      "Added export and confirmed deletion paths covering product, AI, notification, integration, and ML-derived records.",
    sourcePath: projectPath("wizzo"),
    sourceSection: "Actions - Trust and Account Controls",
    evidenceType: "shipped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "xgames-ai-generation",
    entityId: "x-games",
    capability: "ai-product-systems",
    statement:
      "Built a concept-to-play product flow that turns an X post into an AI-generated browser game.",
    sourcePath: projectPath("x-games"),
    sourceSection: "Results - Fast concept-to-play loop",
    evidenceType: "prototyped",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "xgames-game-ux",
    entityId: "x-games",
    capability: "game-ux-systems",
    statement:
      "Designed a browser game experience spanning discovery, direct play, rankings, and playable generated outputs.",
    sourcePath: projectPath("x-games"),
    sourceSection: "Actions - Designed game-card discovery",
    evidenceType: "implemented",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "xgames-creator-system",
    entityId: "x-games",
    capability: "creator-systems",
    statement:
      "Built a creator flow that turns an X post into a generated browser game and publishes it into a shared discovery feed.",
    sourcePath: projectPath("x-games"),
    sourceSection: "Results - Fast concept-to-play loop",
    evidenceType: "prototyped",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "xgames-creative-tech",
    entityId: "x-games",
    capability: "creative-technology",
    statement:
      "Designed game discovery with generated thumbnails, genre labels, creator attribution, play counts, and direct play actions.",
    sourcePath: projectPath("x-games"),
    sourceSection: "Actions - Designed game-card discovery",
    evidenceType: "implemented",
    ownership: "designed",
    confidence: "direct",
  },
  {
    id: "xgames-prototype",
    entityId: "x-games",
    capability: "prototyping",
    statement:
      "Compressed ideation, generation, discovery, and play into a lightweight browser experience.",
    sourcePath: projectPath("x-games"),
    sourceSection: "Results - Fast concept-to-play loop",
    evidenceType: "prototyped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "speakeasy-xr",
    entityId: "speakeasy",
    capability: "xr-spatial",
    statement:
      "Built and iterated a Quest 3 mixed-reality prototype in Unity using Meta Voice SDK, voice recognition, TTS, and multimodal feedback.",
    sourcePath: projectPath("speakeasy"),
    sourceSection: "Build - Implemented the Quest 3 Voice System",
    evidenceType: "implemented",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "speakeasy-voice",
    entityId: "speakeasy",
    capability: "voice-interaction",
    statement:
      "Implemented wake-word activation, intent handling, command variants, TTS, and confidence feedback to reduce reliance on physical controls in XR.",
    sourcePath: projectPath("speakeasy"),
    sourceSection: "Build - Implemented the Quest 3 Voice System",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "speakeasy-accessibility",
    entityId: "speakeasy",
    capability: "accessibility",
    statement:
      "Used literature review, a 42-person survey, participatory co-design, and structured sessions with eight final participants to refine an accessible XR interaction framework.",
    sourcePath: projectPath("speakeasy"),
    sourceSection: "Build - Tested with Eight Participants",
    evidenceType: "researched",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "speakeasy-prototyping",
    entityId: "speakeasy",
    capability: "prototyping",
    statement:
      "Moved from Wizard-of-Oz and ShapesXR trials to two measured Unity prototypes informed by participant feedback.",
    sourcePath: projectPath("speakeasy"),
    sourceSection: "Build - Iterated Across Three Prototype Generations",
    evidenceType: "prototyped",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "soundescape-game-ux",
    entityId: "sound-escape-vr",
    capability: "game-ux-systems",
    statement:
      "Designed a playable spatial music system with sequencer controls, responsive feedback, object interaction, and haptics.",
    sourcePath: projectPath("sound-escape-vr"),
    sourceSection: "Actions - Reworked input and tracking for Quest 3",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "soundescape-xr",
    entityId: "sound-escape-vr",
    capability: "xr-spatial",
    statement:
      "Reworked a Unity spatial music prototype for Meta Quest 3 with device detection, floor tracking, controller profiles, grab ergonomics, collision safeguards, and haptics.",
    sourcePath: projectPath("sound-escape-vr"),
    sourceSection: "Actions - Reworked input and tracking for Quest 3",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "soundescape-creative",
    entityId: "sound-escape-vr",
    capability: "creative-technology",
    statement:
      "Built a four-channel 16-step sequencer and mapped normalized audio bands into generative geometry, lighting, color, and scale.",
    sourcePath: projectPath("sound-escape-vr"),
    sourceSection: "Actions - Mapped eight FFT bands into generative geometry",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "material-design-engineering",
    entityId: "material-explorer",
    capability: "design-engineering",
    statement:
      "Built an interactive React and TypeScript PBR material lab with real-time 3D controls and export workflows.",
    sourcePath: projectPath("material-explorer"),
    sourceSection: "Actions - Built a live React Three Fiber lab",
    evidenceType: "shipped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "material-creator-system",
    entityId: "material-explorer",
    capability: "creator-systems",
    statement:
      "Built browser-based authoring, comparison, persistence, and export tools for iterating on reusable 3D materials.",
    sourcePath: projectPath("material-explorer"),
    sourceSection: "Results - One browser workflow from authoring to export",
    evidenceType: "shipped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "material-creative-tech",
    entityId: "material-explorer",
    capability: "creative-technology",
    statement:
      "Combined interactive 3D tooling, material authoring, live preview, and GLB export in a browser product.",
    sourcePath: projectPath("material-explorer"),
    sourceSection: "Results - One browser workflow from authoring to export",
    evidenceType: "shipped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "material-prototyping",
    entityId: "material-explorer",
    capability: "prototyping",
    statement:
      "Added autosave, history, compare, duplicate, randomize, and import/export tools to speed material iteration.",
    sourcePath: projectPath("material-explorer"),
    sourceSection: "Actions - Added compare and iteration controls",
    evidenceType: "shipped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "geovoice-data",
    entityId: "geovoice",
    capability: "data-visualization",
    statement:
      "Designed layered maps, geospatial analytics, and a dashboard for stakeholder feedback and planning data.",
    sourcePath: projectPath("geovoice"),
    sourceSection: "Actions - Development and Integration",
    evidenceType: "prototyped",
    ownership: "designed",
    confidence: "direct",
  },
  {
    id: "geovoice-workflow",
    entityId: "geovoice",
    capability: "workflow-design",
    statement:
      "Created a centralized collaboration workflow for planners, experts, and community members to contribute geospatial feedback.",
    sourcePath: projectPath("geovoice"),
    sourceSection: "Results - Enhanced Collaboration",
    evidenceType: "prototyped",
    ownership: "designed",
    confidence: "supporting",
  },
  {
    id: "vuln-review-ui",
    entityId: "vulnerability-visualizer",
    capability: "operational-ux",
    statement:
      "Built reviewer-facing search, filters, analysis modes, record inspection, comparison controls, persisted preferences, and export for a large vulnerability dataset.",
    sourcePath: projectPath("vulnerability-visualizer"),
    sourceSection: "Actions - Built normalized review controls",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "vuln-ai-triage",
    entityId: "vulnerability-visualizer",
    capability: "ai-product-systems",
    statement:
      "Exposed supplied AI assessment statuses through explicit analysis modes, filter-impact counts, and manual-versus-AI relationship charts rather than an unexplained verdict.",
    sourcePath: projectPath("vulnerability-visualizer"),
    sourceSection: "Results - Manual-versus-AI review remained visible",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "supporting",
  },
  {
    id: "vuln-data-viz",
    entityId: "vulnerability-visualizer",
    capability: "data-visualization",
    statement:
      "Built severity, analysis-status, risk-factor, trend, and manual-versus-AI assessment visualizations for security review.",
    sourcePath: projectPath("vulnerability-visualizer"),
    sourceSection: "Actions - Visualized manual and AI decision buckets",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "petition-operational-dashboard",
    entityId: "petition-ready",
    capability: "operational-ux",
    statement:
      "Turned bankruptcy intake state into a repeatable queue, readiness score, issue list, evidence snapshot, and next action.",
    sourcePath: projectPath("petition-ready"),
    sourceSection: "Results - One blocker-to-review workflow",
    evidenceType: "prototyped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "petition-ai-review",
    entityId: "petition-ready",
    capability: "human-in-the-loop-ai",
    statement:
      "Built AI-assisted blocker analysis and brief workflows while keeping paralegal and attorney review boundaries visible.",
    sourcePath: projectPath("petition-ready"),
    sourceSection: "Results - Inspectable human-in-the-loop boundary",
    evidenceType: "prototyped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "petition-fallback",
    entityId: "petition-ready",
    capability: "ai-product-systems",
    statement:
      "Implemented structured AI response validation and deterministic fallback analysis so the workflow remains reviewable without model credentials.",
    sourcePath: projectPath("petition-ready"),
    sourceSection: "Actions - Kept deterministic fallback equivalent",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "petition-internal-tool",
    entityId: "petition-ready",
    capability: "internal-tools",
    statement:
      "Built a matter queue and selected-case workspace for blockers, next paralegal actions, and attorney-review items.",
    sourcePath: projectPath("petition-ready"),
    sourceSection: "Actions - Built the paralegal operating console",
    evidenceType: "prototyped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "cse-creative-workflow",
    entityId: "creative-supply-engine",
    capability: "creative-technology",
    statement:
      "Built a repeatable creative automation workflow spanning generation, localization, deterministic layout, and human review.",
    sourcePath: projectPath("creative-supply-engine"),
    sourceSection: "Results - A human review bundle remained the final gate",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "cse-creator-system",
    entityId: "creative-supply-engine",
    capability: "creator-systems",
    statement:
      "Built supporting creative tooling for generating, localizing, reviewing, and packaging reusable campaign assets.",
    sourcePath: projectPath("creative-supply-engine"),
    sourceSection: "Actions - Logged provenance, compliance, and review output",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "supporting",
  },
  {
    id: "cse-ai-assets",
    entityId: "creative-supply-engine",
    capability: "ai-product-systems",
    statement:
      "Implemented local asset reuse first, an OpenAI image-generation path, and graceful placeholder fallback.",
    sourcePath: projectPath("creative-supply-engine"),
    sourceSection: "Actions - Reused approved assets before generating",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "supporting",
  },
  {
    id: "cse-review-tooling",
    entityId: "creative-supply-engine",
    capability: "workflow-design",
    statement:
      "Produced run logs, compliance summaries, and a browser review gallery for localized creative sets.",
    sourcePath: projectPath("creative-supply-engine"),
    sourceSection: "Actions - Logged provenance, compliance, and review output",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "portals-accessibility",
    entityId: "portals",
    capability: "accessibility",
    statement:
      "Implemented spoken portal controls with explicit return phrases and a separate hand-tracked scaling path, while leaving broader accessibility benefits unvalidated.",
    sourcePath: projectPath("portals"),
    sourceSection: "Results - Voice and hand input shared the interaction model",
    evidenceType: "implemented",
    ownership: "led",
    confidence: "supporting",
  },
  {
    id: "portals-xr",
    entityId: "portals",
    capability: "xr-spatial",
    statement:
      "Built a Lens Studio Spectacles scene with three cultural portal states, VoiceML integration, hand tracking, spatial media, and Spectacles Interaction Kit assets.",
    sourcePath: projectPath("portals"),
    sourceSection: "Actions - Integrated cultural media into the Lens scene",
    evidenceType: "implemented",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "portals-voice",
    entityId: "portals",
    capability: "voice-interaction",
    statement:
      "Mapped VoiceML final transcriptions into guarded portal activation, destination routing, and return-home scene states.",
    sourcePath: projectPath("portals"),
    sourceSection: "Actions - Routed spoken destinations into scene states",
    evidenceType: "implemented",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "die-ai-game-ux",
    entityId: "die-ai",
    capability: "game-ux-systems",
    statement:
      "Preserved a complete historical game experience, including playable mechanics, timeline scenes, controls, and original visual assets.",
    sourcePath: projectPath("die-ai"),
    sourceSection: "Actions - Wrapped the unchanged SWF with pinned Ruffle",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "die-ai-creative",
    entityId: "die-ai",
    capability: "creative-technology",
    statement:
      "Restored the unchanged ActionScript game through a pinned Ruffle WebAssembly wrapper.",
    sourcePath: projectPath("die-ai"),
    sourceSection: "Actions - Wrapped the unchanged SWF with pinned Ruffle",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "die-ai-preservation",
    entityId: "die-ai",
    capability: "workflow-design",
    statement:
      "Created a preservation workflow covering original artifacts, modern presentation, provenance, accessibility, runtime QA, release packaging, and archive readiness.",
    sourcePath: projectPath("die-ai"),
    sourceSection: "Actions - Separated artifact, presentation, and evidence layers",
    evidenceType: "implemented",
    ownership: "led",
    confidence: "direct",
  },
]

export const AI_EVIDENCE_CAPABILITIES = new Set<AdaptiveCapability>([
  "ai-product-systems",
  "human-in-the-loop-ai",
  "evaluation-calibration",
  "moderation-qa",
  "model-evaluation",
  "training-data-development",
  "prompt-engineering",
])

export const AI_PROJECT_IDS = new Set(
  EVIDENCE_CATALOG.filter(
    (evidence) =>
      PUBLIC_PROJECT_ID_SET.has(evidence.entityId) &&
      AI_EVIDENCE_CAPABILITIES.has(evidence.capability)
  ).map((evidence) => evidence.entityId)
)
