import type { ProjectEvidence } from "../../../packages/adaptive-focus-core/src"

const projectPath = (projectId: string) => `/projects/${projectId}`

export const PROJECT_EVIDENCE: ProjectEvidence[] = [
  {
    id: "astrocade-hitl-sessions",
    projectId: "astrocade-qa-calibration-tool",
    capability: "human-in-the-loop-ai",
    statement: "Built role-scoped calibration sessions that pair completed game samples with QA and final-review context.",
    sourcePath: projectPath("astrocade-qa-calibration-tool"),
    sourceSection: "Actions - Built role-scoped calibration sessions",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "astrocade-ground-truth",
    projectId: "astrocade-qa-calibration-tool",
    capability: "evaluation-calibration",
    statement: "Separated expected platform decisions from QA decisions to establish explicit ground truth and compute QA correctness.",
    sourcePath: projectPath("astrocade-qa-calibration-tool"),
    sourceSection: "Actions - Established explicit ground truth",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "astrocade-failure-modes",
    projectId: "astrocade-qa-calibration-tool",
    capability: "moderation-qa",
    statement: "Defined constrained QA and final-review failure-mode taxonomies for disagreement, policy, review, and tooling errors.",
    sourcePath: projectPath("astrocade-qa-calibration-tool"),
    sourceSection: "Actions - Defined QA and final-review guardrails",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "astrocade-operating-loop",
    projectId: "astrocade-qa-calibration-tool",
    capability: "operational-ux",
    statement: "Connected sampled context, QA outcomes, ground truth, failure modes, final review, and creator-feedback quality in one repeatable operating loop.",
    sourcePath: projectPath("astrocade-qa-calibration-tool"),
    sourceSection: "Situation - Operating loop",
    evidenceType: "designed",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "astrocade-quality-signals",
    projectId: "astrocade-qa-calibration-tool",
    capability: "data-visualization",
    statement: "Made false rejections, missed blocking issues, precision, recall, reviewer agreement, and feedback actionability visible as quality signals.",
    sourcePath: projectPath("astrocade-qa-calibration-tool"),
    sourceSection: "Results - A measurable quality-control loop",
    evidenceType: "measured",
    ownership: "built",
    outcome: "Created a measurable quality-control loop with explicit legacy-data exclusions.",
    confidence: "direct",
  },
  {
    id: "wizzo-ai-system",
    projectId: "wizzo",
    capability: "ai-product-systems",
    statement: "Designed and shipped an AI-native product system combining mentor chat, execution-aware memory, tools, quests, and connected work context.",
    sourcePath: projectPath("wizzo"),
    sourceSection: "Results - AI Product Proof",
    evidenceType: "shipped",
    ownership: "led",
    outcome: "Shipped a public beta with a live AI mentor and connected work context.",
    confidence: "direct",
  },
  {
    id: "wizzo-full-stack",
    projectId: "wizzo",
    capability: "design-engineering",
    statement: "Built the product with Next.js, TypeScript, Postgres, Drizzle, Neon, Vercel, OpenAI integrations, and Google workspace connectors.",
    sourcePath: projectPath("wizzo"),
    sourceSection: "Actions - Full-Stack Implementation",
    evidenceType: "shipped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "wizzo-product-ownership",
    projectId: "wizzo",
    capability: "product-ownership",
    statement: "Owned the product architecture across chat, memory, quest tracking, achievements, and connector-backed work context.",
    sourcePath: projectPath("wizzo"),
    sourceSection: "Actions - Product System Architecture",
    evidenceType: "designed",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "wizzo-workflows",
    projectId: "wizzo",
    capability: "workflow-design",
    statement: "Created mentor workflows for goal planning, progress reflection, grounded research, connected notes, and voice-supported follow-up.",
    sourcePath: projectPath("wizzo"),
    sourceSection: "Actions - AI Workflow Surfaces",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "wizzo-trust-controls",
    projectId: "wizzo",
    capability: "privacy-trust",
    statement: "Added export and confirmed deletion paths covering product, AI, notification, integration, and ML-derived records.",
    sourcePath: projectPath("wizzo"),
    sourceSection: "Actions - Trust and Account Controls",
    evidenceType: "shipped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "xgames-ai-generation",
    projectId: "x-games",
    capability: "ai-product-systems",
    statement: "Built a concept-to-play product flow that turns an X post into an AI-generated browser game.",
    sourcePath: projectPath("x-games"),
    sourceSection: "Results - Fast concept-to-play loop",
    evidenceType: "prototyped",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "xgames-creative-tech",
    projectId: "x-games",
    capability: "creative-technology",
    statement: "Designed game discovery with generated thumbnails, genre labels, creator attribution, play counts, and direct play actions.",
    sourcePath: projectPath("x-games"),
    sourceSection: "Actions - Designed game-card discovery",
    evidenceType: "implemented",
    ownership: "designed",
    confidence: "direct",
  },
  {
    id: "xgames-prototype",
    projectId: "x-games",
    capability: "prototyping",
    statement: "Compressed ideation, generation, discovery, and play into a lightweight browser experience.",
    sourcePath: projectPath("x-games"),
    sourceSection: "Results - Fast concept-to-play loop",
    evidenceType: "prototyped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "petition-operational-dashboard",
    projectId: "petition-ready",
    capability: "operational-ux",
    statement: "Turned bankruptcy intake state into a repeatable queue, readiness score, issue list, evidence snapshot, and next action.",
    sourcePath: projectPath("petition-ready"),
    sourceSection: "Results - One blocker-to-review workflow",
    evidenceType: "prototyped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "petition-ai-review",
    projectId: "petition-ready",
    capability: "human-in-the-loop-ai",
    statement: "Built AI-assisted blocker analysis and brief workflows while keeping paralegal and attorney review boundaries visible.",
    sourcePath: projectPath("petition-ready"),
    sourceSection: "Results - Inspectable human-in-the-loop boundary",
    evidenceType: "prototyped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "petition-fallback",
    projectId: "petition-ready",
    capability: "ai-product-systems",
    statement: "Implemented structured AI response validation and deterministic fallback analysis so the workflow remains reviewable without model credentials.",
    sourcePath: projectPath("petition-ready"),
    sourceSection: "Actions - Kept deterministic fallback equivalent",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "petition-internal-tool",
    projectId: "petition-ready",
    capability: "internal-tools",
    statement: "Built a matter queue and selected-case workspace for blockers, next paralegal actions, and attorney-review items.",
    sourcePath: projectPath("petition-ready"),
    sourceSection: "Actions - Built the paralegal operating console",
    evidenceType: "prototyped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "cse-creative-workflow",
    projectId: "creative-supply-engine",
    capability: "creative-technology",
    statement: "Built a repeatable creative automation workflow spanning generation, localization, deterministic layout, and human review.",
    sourcePath: projectPath("creative-supply-engine"),
    sourceSection: "Results - A human review bundle remained the final gate",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "cse-ai-assets",
    projectId: "creative-supply-engine",
    capability: "ai-product-systems",
    statement: "Implemented local asset reuse first, an OpenAI image-generation path, and graceful placeholder fallback.",
    sourcePath: projectPath("creative-supply-engine"),
    sourceSection: "Actions - Reused approved assets before generating",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "supporting",
  },
  {
    id: "cse-review-tooling",
    projectId: "creative-supply-engine",
    capability: "workflow-design",
    statement: "Produced run logs, compliance summaries, and a browser review gallery for localized creative sets.",
    sourcePath: projectPath("creative-supply-engine"),
    sourceSection: "Actions - Logged provenance, compliance, and review output",
    evidenceType: "implemented",
    ownership: "built",
    outcome: "Generated twelve sample campaign outputs and passed documented compliance checks.",
    confidence: "direct",
  },
  {
    id: "vuln-review-ui",
    projectId: "vulnerability-visualizer",
    capability: "operational-ux",
    statement: "Built reviewer-facing search, filters, analysis modes, record inspection, comparison controls, persisted preferences, and export for a 236,656-record vulnerability dataset.",
    sourcePath: projectPath("vulnerability-visualizer"),
    sourceSection: "Actions - Built normalized review controls",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "vuln-ai-triage",
    projectId: "vulnerability-visualizer",
    capability: "ai-product-systems",
    statement: "Exposed supplied AI assessment statuses through explicit analysis modes, filter-impact counts, and manual-versus-AI relationship charts rather than an unexplained verdict.",
    sourcePath: projectPath("vulnerability-visualizer"),
    sourceSection: "Results - Manual-versus-AI review remained visible",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "supporting",
  },
  {
    id: "vuln-data-viz",
    projectId: "vulnerability-visualizer",
    capability: "data-visualization",
    statement: "Built severity, analysis-status, risk-factor, trend, and manual-versus-AI assessment visualizations for security review.",
    sourcePath: projectPath("vulnerability-visualizer"),
    sourceSection: "Actions - Visualized manual and AI decision buckets",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "speakeasy-xr",
    projectId: "speakeasy",
    capability: "xr-spatial",
    statement: "Built and iterated a Quest 3 mixed-reality prototype in Unity using Meta Voice SDK, voice recognition, TTS, and multimodal feedback.",
    sourcePath: projectPath("speakeasy"),
    sourceSection: "Build - Implemented the Quest 3 Voice System",
    evidenceType: "implemented",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "speakeasy-voice",
    projectId: "speakeasy",
    capability: "voice-interaction",
    statement: "Implemented wake-word activation, intent handling, command variants, TTS, and confidence feedback to reduce reliance on physical controls in XR.",
    sourcePath: projectPath("speakeasy"),
    sourceSection: "Build - Implemented the Quest 3 Voice System",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "speakeasy-accessibility",
    projectId: "speakeasy",
    capability: "accessibility",
    statement: "Used literature review, a 42-person survey, participatory co-design, and structured sessions with eight final participants to refine an accessible XR interaction framework.",
    sourcePath: projectPath("speakeasy"),
    sourceSection: "Build - Tested with Eight Participants",
    evidenceType: "researched",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "speakeasy-prototyping",
    projectId: "speakeasy",
    capability: "prototyping",
    statement: "Moved from Wizard-of-Oz and ShapesXR trials to two measured Unity prototypes informed by participant feedback.",
    sourcePath: projectPath("speakeasy"),
    sourceSection: "Build - Iterated Across Three Prototype Generations",
    evidenceType: "prototyped",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "gaia-spatial",
    projectId: "gaia",
    capability: "xr-spatial",
    statement: "Designed and developed Unity spatial-computing prototypes for Starbucks employee and customer contexts.",
    sourcePath: projectPath("gaia"),
    sourceSection: "Actions - Development",
    evidenceType: "prototyped",
    ownership: "designed",
    confidence: "direct",
  },
  {
    id: "gaia-operations",
    projectId: "gaia",
    capability: "operational-ux",
    statement: "Researched employee and customer needs and aligned spatial prototypes with operational requirements.",
    sourcePath: projectPath("gaia"),
    sourceSection: "Actions - Collaboration",
    evidenceType: "researched",
    ownership: "designed",
    confidence: "supporting",
  },
  {
    id: "transcribe-accessibility",
    projectId: "transcribe",
    capability: "accessibility",
    statement: "Designed and tested a real-time transcription tool with an explicit focus on people with disabilities.",
    sourcePath: projectPath("transcribe"),
    sourceSection: "Actions - User Research",
    evidenceType: "researched",
    ownership: "designed",
    confidence: "direct",
  },
  {
    id: "transcribe-voice",
    projectId: "transcribe",
    capability: "voice-interaction",
    statement: "Integrated Google Cloud Speech-to-Text into a React application for real-time transcription.",
    sourcePath: projectPath("transcribe"),
    sourceSection: "Actions - Development",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "transcribe-operational",
    projectId: "transcribe",
    capability: "operational-ux",
    statement: "Integrated the transcription application into an existing operational framework.",
    sourcePath: projectPath("transcribe"),
    sourceSection: "Actions - Integration",
    evidenceType: "implemented",
    ownership: "contributed",
    confidence: "supporting",
  },
  {
    id: "material-design-engineering",
    projectId: "material-explorer",
    capability: "design-engineering",
    statement: "Built an interactive React and TypeScript PBR material lab with real-time 3D controls and export workflows.",
    sourcePath: projectPath("material-explorer"),
    sourceSection: "Actions - Built a live React Three Fiber lab",
    evidenceType: "shipped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "material-creative-tech",
    projectId: "material-explorer",
    capability: "creative-technology",
    statement: "Combined interactive 3D tooling, material authoring, live preview, and GLB export in a browser product.",
    sourcePath: projectPath("material-explorer"),
    sourceSection: "Results - One browser workflow from authoring to export",
    evidenceType: "shipped",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "material-prototyping",
    projectId: "material-explorer",
    capability: "prototyping",
    statement: "Added autosave, history, compare, duplicate, randomize, and import/export tools to speed material iteration.",
    sourcePath: projectPath("material-explorer"),
    sourceSection: "Actions - Added compare and iteration controls",
    evidenceType: "shipped",
    ownership: "built",
    outcome: "Reduced friction for testing and communicating material ideas.",
    confidence: "direct",
  },
  {
    id: "apt-workflow",
    projectId: "apt-plus",
    capability: "workflow-design",
    statement: "Led field research, rapid prototyping, and workflow automation for manufacturing time-study processes.",
    sourcePath: projectPath("apt-plus"),
    sourceSection: "Actions - Overview",
    evidenceType: "shipped",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "apt-operations",
    projectId: "apt-plus",
    capability: "operational-ux",
    statement: "Reduced manual data-entry and validation work through production workflow tooling.",
    sourcePath: projectPath("apt-plus"),
    sourceSection: "Results - Increased Efficiency and Accuracy",
    evidenceType: "measured",
    ownership: "led",
    outcome: "Documented approximately $1M in annual savings per plant.",
    confidence: "direct",
  },
  {
    id: "apt-product-ownership",
    projectId: "apt-plus",
    capability: "product-ownership",
    statement: "Led design and engineering strategy across project management, software engineering, research, and business stakeholders.",
    sourcePath: projectPath("apt-plus"),
    sourceSection: "Actions - Overview",
    evidenceType: "shipped",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "geovoice-data",
    projectId: "geovoice",
    capability: "data-visualization",
    statement: "Designed layered maps, geospatial analytics, and a dashboard for stakeholder feedback and planning data.",
    sourcePath: projectPath("geovoice"),
    sourceSection: "Actions - Development and Integration",
    evidenceType: "prototyped",
    ownership: "designed",
    confidence: "direct",
  },
  {
    id: "geovoice-workflow",
    projectId: "geovoice",
    capability: "workflow-design",
    statement: "Created a centralized collaboration workflow for planners, experts, and community members to contribute geospatial feedback.",
    sourcePath: projectPath("geovoice"),
    sourceSection: "Results - Enhanced Collaboration",
    evidenceType: "prototyped",
    ownership: "designed",
    confidence: "supporting",
  },
  {
    id: "soundescape-xr",
    projectId: "sound-escape-vr",
    capability: "xr-spatial",
    statement: "Reworked a Unity 2022 spatial music prototype for Meta Quest 3 with explicit device detection, floor tracking, controller profiles, grab ergonomics, collision safeguards, and haptics.",
    sourcePath: projectPath("sound-escape-vr"),
    sourceSection: "Actions - Reworked input and tracking for Quest 3",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "soundescape-creative",
    projectId: "sound-escape-vr",
    capability: "creative-technology",
    statement: "Built a four-channel 16-step sequencer and mapped eight normalized FFT bands into Koch-line emission, trail behavior, lighting, color, and object scale.",
    sourcePath: projectPath("sound-escape-vr"),
    sourceSection: "Actions - Mapped eight FFT bands into generative geometry",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "portals-accessibility",
    projectId: "portals",
    capability: "accessibility",
    statement: "Implemented spoken portal controls with three explicit return phrases and a separate hand-tracked scaling path, while leaving broader accessibility benefits unvalidated.",
    sourcePath: projectPath("portals"),
    sourceSection: "Results - Voice and hand input shared the interaction model",
    evidenceType: "implemented",
    ownership: "led",
    confidence: "supporting",
  },
  {
    id: "portals-xr",
    projectId: "portals",
    capability: "xr-spatial",
    statement: "Built a Lens Studio Spectacles scene with three cultural portal states, VoiceML integration, hand tracking, spatial media, and Spectacles Interaction Kit assets.",
    sourcePath: projectPath("portals"),
    sourceSection: "Actions - Integrated cultural media into the Lens scene",
    evidenceType: "implemented",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "portals-voice",
    projectId: "portals",
    capability: "voice-interaction",
    statement: "Mapped VoiceML final transcriptions into guarded portal activation, destination routing, and return-home scene states.",
    sourcePath: projectPath("portals"),
    sourceSection: "Actions - Routed spoken destinations into scene states",
    evidenceType: "implemented",
    ownership: "led",
    confidence: "direct",
  },
  {
    id: "die-ai-creative",
    projectId: "die-ai",
    capability: "creative-technology",
    statement: "Preserved original ActionScript game mechanics, timeline scenes, and visual assets while restoring the unchanged SWF through a pinned Ruffle WebAssembly wrapper.",
    sourcePath: projectPath("die-ai"),
    sourceSection: "Actions - Wrapped the unchanged SWF with pinned Ruffle",
    evidenceType: "implemented",
    ownership: "built",
    confidence: "direct",
  },
  {
    id: "die-ai-preservation",
    projectId: "die-ai",
    capability: "workflow-design",
    statement: "Created a three-layer preservation workflow covering original artifacts, modern presentation, provenance, checksums, licensing, accessibility, runtime QA, release packaging, and archive readiness.",
    sourcePath: projectPath("die-ai"),
    sourceSection: "Actions - Separated artifact, presentation, and evidence layers",
    evidenceType: "implemented",
    ownership: "led",
    confidence: "direct",
  },
]

export const AI_EVIDENCE_CAPABILITIES = new Set([
  "ai-product-systems",
  "human-in-the-loop-ai",
  "evaluation-calibration",
  "moderation-qa",
])

export const AI_PROJECT_IDS = new Set(
  PROJECT_EVIDENCE.filter((evidence) => AI_EVIDENCE_CAPABILITIES.has(evidence.capability)).map(
    (evidence) => evidence.projectId
  )
)
